# --- Aşama 1: Build ---
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY SecOpsLite.Worker/SecOpsLite.Worker.csproj SecOpsLite.Worker/
RUN dotnet restore SecOpsLite.Worker/SecOpsLite.Worker.csproj

COPY SecOpsLite.Worker/ SecOpsLite.Worker/
WORKDIR /src/SecOpsLite.Worker
RUN dotnet publish -c Release -o /app

# --- Aşama 2: Runtime ---
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "SecOpsLite.Worker.dll"]